development:
  adapter: postgresql
  encoding: unicode
  database: mods_gta_dev
  pool: 5
  username: admin
  password: password

test:
  adapter: postgresql
  encoding: unicode
  database: mods_gta_test
  pool: 5
  username: admin
  password: password

production:
  adapter: postgresql
  encoding: unicode
  database: mods_gta_production
  pool: 5
  username: admin
  password: password