development:
  adapter: postgresql
  encoding: unicode
  database: mods_gta_dev
  pool: 5
  username: admin
  password: password
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mods_gta_test
  pool: 5
  username: admin
  password: password
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: mods_gtav_production
  pool: 5
  host: localhost
  username: gtaadmin
  password: gtapass