production:
  sessions:
    default:
      database: mods_gtav_production
      hosts:
        - localhost:27017

development:
  sessions:
    default:
      database: mods_gtav_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: mods_gtav_test
      hosts:
        - localhost:27017

staging:
  sessions:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>